# Generated by Django 4.1.5 on 2023-02-24 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auth_users_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='menuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='sign_in',
        ),
        migrations.AddField(
            model_name='menu',
            name='category_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Category_ID', to='myapp.menucategory'),
        ),
    ]
