# Generated by Django 4.1.5 on 2023-03-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_menucategory_delete_sign_in_menu_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('Coffee_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Coffee_Name', models.CharField(max_length=100)),
                ('Coffee_Price', models.FloatField()),
                ('Coffee_Describtion', models.CharField(max_length=500)),
                ('Coffee_Depot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('Dessert_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Dessert_Name', models.CharField(max_length=100)),
                ('Dessert_Price', models.FloatField()),
                ('Dessert_Describtion', models.CharField(max_length=500)),
                ('Dessert_Depot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('Meal_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Meal_Name', models.CharField(max_length=100)),
                ('Meal_Price', models.FloatField()),
                ('Meal_Describtion', models.CharField(max_length=500)),
                ('Meal_Depot', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='auth_users',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category_Id',
        ),
        migrations.DeleteModel(
            name='sign_up',
        ),
        migrations.DeleteModel(
            name='menu',
        ),
        migrations.DeleteModel(
            name='menuCategory',
        ),
    ]
