# Generated by Django 4.1.5 on 2023-03-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_coffee_coffee_id_remove_dessert_dessert_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='breakfast',
            fields=[
                ('breakfast_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('breakfast_Price', models.FloatField()),
                ('breakfast_Describtion', models.CharField(max_length=2000)),
                ('breakfast_Depot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dinner',
            fields=[
                ('dinner_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dinner_Price', models.FloatField()),
                ('dinner_Describtion', models.CharField(max_length=2000)),
                ('dinner_Depot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='lunch',
            fields=[
                ('lunch_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lunch_Price', models.FloatField()),
                ('lunch_Describtion', models.CharField(max_length=2000)),
                ('lunch_Depot', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
