# Generated by Django 4.1.5 on 2023-03-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_breakfast_dinner_lunch_delete_meal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
